### ISSUE TITLE
Alternative solution for the problem of SPI sending garbage value after programming the master

### ISSUE THREAD

**Issue by pranav-sankhe** [Electrical-Subsystem/Functionality-Test#2]
@singhalanirudh18  instead of restarting the OBC isn't there a more clean way (less farzi) to solve the same issue.

**Comment by singhalanirudh18** [comment]
I didn't explore any other solution once SPI started working. And I didn't find the solution so farzi either.

**Comment by pranav-sankhe** [comment]
Do you plan to investigate the issue further or should I close the issue? Do let me know by adding a comment here or personally messaging me.
